### ISSUE TITLE
Python port

### ISSUE THREAD

**Issue by fbidu** [dschenkelman/feature-change#6]
Hi, I don't know if this project is currently maintained but I just saw @dschenkelman's talk on API's dirty secrets and found the `feature-change` approach really interesting. I'm planning on using it in the next couple of weeks so I wrote a port of this project for Python

If anyone's interested, [here's the project](https://github.com/fbidu/feature-change)

Thank you!

**Comment by dschenkelman** [comment]
Hey @fbidu, thanks for sharing. Happy you found the talk and the project useful!

The project is used internally at Auth0, but there is no "active development" on this. It is meant to be simple and is mostly code complete.

I will close the issue so people can still find it but it does not remain open, as it is something readers could interpret as "pending work".

**Comment by fbidu** [comment]
Thank you, @dschenkelman!

All the best
